### ISSUE TITLE
Truncation of text

### ISSUE THREAD

**Issue by Stratofish** [Claromentis/cla-cmp-rss-reader#1]
Currently each line in the feed that gets displayed is truncated to 50 chars. This should be an attribute of the component as sometimes the full text is required.

Maybe some way to specify length for specific RSS field too.

**Comment by astax-t** [comment]
This was fixed in https://github.com/Claromentis/cla-cmp-rss-reader/commit/067bad18b4384a984a73c2a484b50445fbfdbe5d
