### ISSUE TITLE
Incorrect sorting if a custom date format is set in framework

### ISSUE THREAD

**Issue by piddl0r** [Claromentis/cla-cmp-rss-reader#2]
When a custom date format is set in the config ($date_format[]) the sorting of the RSS items is incorrectly sorted.

**Comment by olganovosad** [comment]
hello,

client has reported similar issue with sorting. I've been able to replicate the issue on review: https://discover.claromentis.com/forms/tickets/view/007196#_form

Code:  <component class="TemplaterComponentRSS" feed_1="http://evilhrlady.org/feed" feed_2="https://americanstaffing.net/feeds/staffing-news/rss2/" feed_3="http://www.staffingindustry.com/services/rss/blog-rss" display="10" />
		</div>

**Comment by astax-t** [comment]
This should be fixed in 2.0.0
